classname=org.opensearch.plugin.zentity.ZentityPluginMinimal
description=Zentity Entity Resolution Plugin for OpenSearch
opensearch.version=2.17.0
java.version=17
name=zentity
version=1.8.3-opensearch-2.17.0
